Add feature brainstorming
grissius/markup-editor-ui pull request #12
Opened 2017-10-23 08:14 UTC by grissius

2017-10-25 00:29 UTC, pchmelar commented
Ok

2017-10-25 15:56 UTC, pet-e requested changes

2017-10-25 15:56 UTC, pet-e commented on 1.adoc
> +
- Synchronizované scrollování editoru a preview
- Možnost se proklikávat z preview do editoru
- Přesouvání celých kapitol v dokumentu

2017-10-25 15:56 UTC, pet-e commented on 1.adoc
> +- Náhled dokumentu
- Živý náhled dokumentu

2017-10-25 19:15 UTC, pet-e requested changes

2017-10-25 19:15 UTC, pet-e commented on 1.adoc
> +- Diff (indikace změněných řídek)
řídek -> řádek

2017-10-25 19:15 UTC, pet-e commented on 1.adoc
> +- Command pallette
Otazka: mame nekde receno co je vlastne obsazeno v command palete?

2017-10-26 07:48 UTC, smolijar commented on 1.adoc
> +
> Popup s klávesovou zkratkou při kliknutí na tlačítko které má klávesovou zkratku

Tohle nechapu. Jako ze kdyz mas dve klavesovy zrkatky `Ctr+a` a `Ctr+b` tak ze ti nekde pri zmacknuti `Ctrl` vyskoci popup, ze mas zmacknout `a` pro foo a `b` pro bar? Pokud jo tak mi to pripada dost rusivy.

Zbytek featur se mi libi, ale nevim jestli je stihnu implementovat v Hi-fi. Takze do brainstormu bych je klidne zaradil, ale do tasklistu se mi moc nechce :D Ale pokud na tom trvas tak to tam dame a ja se budu snazit. Hunka rikal, ze bude schovivavej k hi-fi, ze se mu to zda narocny.

2017-10-26 08:30 UTC, grissius commented on 1.adoc
> +- Command pallette
Ano, https://github.com/grissius/markup-editor-ui/pull/15/files#diff-4ef1a5ac550bd700efc6a70155345bdaR71

2017-10-26 08:32 UTC, grissius commented on 1.adoc
> +- Náhled dokumentu
fixed 7affcf924f5eb293b4944a19225b5be60774ef8a

2017-10-26 08:32 UTC, grissius commented on 1.adoc
> +
Ostatni fixed 7affcf924f5eb293b4944a19225b5be60774ef8a

2017-10-26 08:32 UTC, grissius commented on 1.adoc
> +- Diff (indikace změněných řídek)
fixed 7affcf924f5eb293b4944a19225b5be60774ef8a

2017-10-26 09:02 UTC, pet-e commented
Ja to myslel tak, ze pokud kliknes na tlacitko v command palete, ktery ale ma I klavesovou zkratku, tak nekde v rohu se na dve vteriny nerusive zobrazi ta zkratka a pak zase sama zmizi (takovej hint). Ale urcite na tom NEtrvam.

From: Jaroslav Šmolík
Sent: Thursday, October 26, 2017 9:48 AM
To: grissius/markup-editor-ui
Cc: pet-e; Comment
Subject: {Disarmed} Re: [grissius/markup-editor-ui] Add feature brainstorming (#12)

@grissius commented on this pull request.

In 1.adoc:
> +- Vyhledávání v dokumentu
+- Autocomplete
+- Syntax highlight
+- Náhled dokumentu
+- Dvousloupečkový náhled (zdrojový kód vedle náhledu hotového dokumentu)
+- Command pallette
+- Document outline preview
+- Spellcheck
+- Čísla řádek (toggle)
+- Zalamování textu
+- Sbalování sekcí kódu
+- Distraction free mód
+- Diff (indikace změněných řídek)
+- Běžné klávesové zkratky
+- Status bar
+
Popup s klávesovou zkratkou při kliknutí na tlačítko které má klávesovou zkratku
Tohle nechapu. Jako ze kdyz mas dve klavesovy zrkatky Ctr+a a Ctr+b tak ze ti nekde pri zmacknuti Ctrl vyskoci popup, ze mas zmacknout a pro foo a b pro bar? Pokud jo tak mi to pripada dost rusivy.
Zbytek featur se mi libi, ale nevim jestli je stihnu implementovat v Hi-fi. Takze do brainstormu bych je klidne zaradil, ale do tasklistu se mi moc nechce :D Ale pokud na tom trvas tak to tam dame a ja se budu snazit. Hunka rikal, ze bude schovivavej k hi-fi, ze se mu to zda narocny.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/grissius/markup-editor-ui","title":"grissius/markup-editor-ui","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/grissius/markup-editor-ui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@grissius commented on #12"}],"action":{"name":"View Pull Request","url":"https://github.com/grissius/markup-editor-ui/pull/12#discussion_r146916445"}}}

2017-10-26 10:20 UTC, grissius commented
Rozumim. Libi se mi to uzivatelsky, ale na provedeni bych se jeste zamyslel a zatim to nezminoval. Libi se mit treba reseni z VS Code, kde vidis zkratky v pallette.

![image](https://user-images.githubusercontent.com/24388536/32047978-1422e52a-ba48-11e7-8eed-092047a600e4.png)

2017-10-26 11:07 UTC, pet-e commented
ok

On 2017-10-26 12:20, Jaroslav Šmolík wrote:
> Rozumim. Libi se mi to uzivatelsky, ale na provedeni bych se jeste
> zamyslel a zatim to nezminoval. Libi se mit treba reseni z VS Code,
> kde vidis zkratky v pallette. 
> 
>  [1] 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [2], or mute the
> thread [3].
> 
> 	*
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/grissius/markup-editor-ui","title":"grissius/markup-editor-ui","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
> in
> GitHub","url":"https://github.com/grissius/markup-editor-ui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@grissius
> in #12: Rozumim. Libi se mi to uzivatelsky, ale na provedeni bych se
> jeste zamyslel a zatim to nezminoval. Libi se mit treba reseni z VS
> Code, kde vidis zkratky v
> pallette.\r\n\r\n![image](https://user-images.githubusercontent.com/24388536/32047978-1422e52a-ba48-11e7-8eed-092047a600e4.png)\r\n"}],"action":{"name":"View
> Pull
> Request","url":"https://github.com/grissius/markup-editor-ui/pull/12#issuecomment-339621082"}}}
> 
> Links:
> ------
> [1]
> https://user-images.githubusercontent.com/24388536/32047978-1422e52a-ba48-11e7-8eed-092047a600e4.png
> [2] https://github.com/grissius/markup-editor-ui/pull/12#issuecomment-339621082
> [3]
> https://github.com/notifications/unsubscribe-auth/AfkDLDq6mZlJYG1AAsjN6wI-XqmfzKoOks5swF0CgaJpZM4QCczf

2017-10-26 18:34 UTC, slowbackspace commented
ok

2017-10-26 18:43 UTC, merged